// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"fmt"
	"log/slog"
	"object-storage/internal/config"
	"object-storage/internal/handlers/grpc"
	"object-storage/internal/storage"
	"os"

	"github.com/nats-io/nats.go"
)

// Injectors from wire.go:

func Init() (*App, func(), error) {
	configConfig := config.New()
	logger := initLogger(configConfig)
	conn, cleanup, err := initNats(configConfig)
	if err != nil {
		return nil, nil, err
	}
	objectStorage, err := storage.New(conn, configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	server := grpc.New(objectStorage)
	app := newApp(configConfig, logger, server)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func initLogger(cfg *config.Config) *slog.Logger {
	var level slog.Level

	switch cfg.Logger.Level {
	case "debug":
		level = slog.LevelDebug
	case "info":
		level = slog.LevelInfo
	}

	return slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: level}))
}

func initNats(cfg *config.Config) (*nats.Conn, func(), error) {
	nc, err := nats.Connect(fmt.Sprintf("nats://%s:%d", cfg.Nats.Host, cfg.Nats.Port))
	if err != nil {
		return nil, nil, err
	}
	return nc, func() {
		nc.Close()
	}, nil
}
